version: "2"

run:
  timeout: 5m
  go: '1.25'

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter
    - unused        # Check for unused code
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible, flexible linter
    - gosec         # Security checks
    - gocritic      # Opinionated Go linter
    - bodyclose     # Check HTTP response body is closed
    - nilerr        # Find code returning nil even if it checks err != nil
    - errorlint     # Find misuses of errors
    - exhaustive    # Check exhaustiveness of enum switch statements

  exclusions:
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - gosec
          - gocritic

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true

    revive:
      confidence: 0.8

    gosec:
      excludes:
        - G104 # Audit errors not checked. errcheck handles this

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - commentedOutCode

formatters:
  enable:
    - gofmt         # Check formatting
    - goimports     # Check imports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0